services:
  php:
    build:
      context: backend/php_service
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - webshop_net
    volumes:
      - ./backend/php_service/public:/var/www/html/public
      - ./backend/php_service/src:/var/www/html/src
    ports:
      - "8080:80"

  frontend:
    build:
      context: frontend
    ports:
      - "3000:80"
    networks:
      - webshop_net
    depends_on:
      - gateway

  gateway:
    image: nginx:alpine
    networks:
      - webshop_net
    volumes:
      - ./gateway/default.conf:/etc/nginx/default.conf
    ports:
      - "80:80"
    depends_on:
      - python
      - php

networks:
  webshop_net:
    external: true
