version: '3.9'

services:
  python:
    build:
      context: backend/python_service
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - webshop_net
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=userdb
      - DB_PORT=3306

  gateway:
    image: nginx:alpine
    networks:
      - webshop_net
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - python
      - php
      - frontend
      
networks:
  webshop_net:
    external: true
