FROM jenkins/jenkins:lts

USER root

# Cài Docker CLI và Docker Compose (giữ nguyên như bạn đã làm)
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common \
    lsb-release \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - \
    && echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list \
    && apt-get update && apt-get install -y docker-ce-cli

RUN curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose

# RUN usermod -aG docker jenkins
# RUN groupadd docker || true && usermod -aG docker jenkins

USER jenkins

# Chạy Jenkins mặc định
CMD ["jenkins.sh"]
