pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        git(
          url: 'https://github.com/Lunaricku/webshop.git',
          branch: 'test'
        )
      }
    }

    stage('Deploy Database') {
      steps {
        sh """
          docker-compose -f docker-compose.db.yml down -v
          docker-compose -f docker-compose.db.yml up -d
        """
      }
    }

    stage('Deploy Python Service') {
      steps {
        sh """
          docker-compose -f docker-compose.python.yml down
          docker-compose -f docker-compose.python.yml up -d --build
        """
      }
    }

    stage('Deploy PHP + Frontend + Gateway') {
      steps {
        sh """
          docker-compose -f docker-compose.php.yml down
          docker-compose -f docker-compose.php.yml up -d --build
        """
        sh 'docker ps --format "table {{$Names}}\t{{$Image}}\t{{$Ports}}"'
      }
    }
  }

  post {
    success {
      echo 'Deployment succeeded!'
    }
    failure {
      echo 'Deployment failed!'
    }
  }
}
