pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        git(
          url: 'https://github.com/Lunaricku/webshop.git',
          branch: 'test'
        )
      }
    }

    stage('Deploy') {
      steps {
        dir('/var/jenkins_home/workspace/webshop') {
          sh """
            docker-compose down
            docker-compose up -d --build
          """
          sh 'docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Ports}}"'
        }
      }
    }
  }

  post {
    success {
      echo 'Deployment succeeded!'
    }
    failure {
      echo 'Deployment failed!'
    }
  }
}
